/* build-rc.mjs — мини «компилятор ресурсов»: парсит .rc (ICON/BITMAP "файл") и вшивает
 * байты в C-массивы, которые линкуются в .wasm. LoadIcon/LoadBitmap достают их по id.
 * Usage: node scripts/build-rc.mjs <app.rc> <out_res.c>  */
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';

const [, , rcPath, outPath] = process.argv;
if (!rcPath || !outPath) { console.error('usage: build-rc.mjs <rc> <out.c>'); process.exit(1); }

const dir = dirname(rcPath);
const mime = { ico: 'image/x-icon', bmp: 'image/bmp', png: 'image/png', cur: 'image/x-icon' };
const res = [];
for (const line of readFileSync(rcPath, 'utf8').split('\n')) {
  const m = line.match(/^\s*(\d+)\s+(ICON|BITMAP|RCDATA)\s+"([^"]+)"/i);
  if (!m) continue;
  const bytes = readFileSync(resolve(dir, m[3]));
  const ext = m[3].split('.').pop().toLowerCase();
  res.push({ id: +m[1], mime: mime[ext] || 'application/octet-stream', bytes });
}

// res_N — STATIC модуль-локальные данные; lcc экспортирует non-static функции-аксессоры,
// фасад winweb достаёт ресурсы через них (см. switch-аксессоры ниже).
let c = `/* generated by build-rc.mjs from ${rcPath} — do not edit */\n`;
c += 'typedef struct { int id; const char* mime; const unsigned char* data; int len; } WinwebRes;\n';
res.forEach((r, i) => { c += `static const unsigned char res_${i}[] = {${[...r.bytes].join(',')}};\n`; });
c += 'static const WinwebRes winweb_res[] = {\n';
res.forEach((r, i) => { c += `  {${r.id}, "${r.mime}", res_${i}, sizeof res_${i}},\n`; });
c += '};\n';
c += `const WinwebRes* winweb_res_table(void){ return winweb_res; }\n`;
c += `int winweb_res_n(void){ return ${res.length}; }\n`;
// lcc-safe скалярные аксессоры: значения через switch, БЕЗ агрегатного инициализатора
// struct-массива (его lcc компилирует неверно). Фасад winweb читает только эти скаляры.
const sw = (sig, arm) => `${sig}{\n  switch(i){\n${res.map((r, i) => `    case ${i}: return ${arm(r, i)};\n`).join('')}  }\n  return 0;\n}\n`;
c += sw('int winweb_res_id_at(int i)', (r) => r.id);
c += sw('const char* winweb_res_mime_at(int i)', (r) => `"${r.mime}"`);
c += sw('const unsigned char* winweb_res_data_at(int i)', (_r, i) => `res_${i}`);
c += sw('int winweb_res_len_at(int i)', (_r, i) => `sizeof res_${i}`);
writeFileSync(outPath, c);
console.log(`build-rc: embedded ${res.length} resources (${res.map((r) => r.id).join(',')}) -> ${outPath}`);
